trigger:
  # start a new build for every push
  batch: False
  branches:
    include:
      - develop

jobs:
- job: ARMV6_Emulated_GCC
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
#- script: |
#    docker run --rm --privileged multiarch/qemu-user-static:register --reset
#    ls /proc/sys/fs/binfmt_misc/
#  condition: not(startsWith(variables['CONFIG'], 'linux_64'))
#  displayName: 'Configure binfmt_misc'

  - script: |
    echo "FROM openblas/alpine:arm32
          COPY . /tmp/openblas
          RUN mkdir /tmp/openblas/build                             &&  \
          cd /tmp/openblas/build                                &&  \
          CC=gcc cmake -D DYNAMIC_ARCH=OFF                  \
                                 -D TARGET=ARMV6             \
                                 -D BUILD_SHARED_LIBS=ON              \
                                 -D BUILD_WITHOUT_LAPACK=ON           \
                                 -D BUILD_WITHOUT_CBLAS=ON            \
                                 -D CMAKE_BUILD_TYPE=Release ../  &&  \
          cmake --build ." > Dockerfile
    docker build .
  displayName: 'Run ARMV6 docker build'
